THEME: error red needs to be darker for AA compliance
MetLifeLegalPlans/wui pull request #24
Opened 2020-10-01 02:03 UTC by laks12metlife

The color contrast for the following 2 error types in portunus don't meet the AA standard.  One is on the form helper text and the other is general form errors.  I figured making this change would be easier to do once in `wui `rather than using `makeStyles` multiple times in the individual components.  But if you think applying the style to each component in portunus using `makeStyles` is better, let me know!

FYI the images below are using the AA compliant darker shade of red (#DE0007) not the default mui shade. 

![wui_helpererror](https://user-images.githubusercontent.com/64965386/94757248-b221b380-0367-11eb-96c2-31d5f1ffb011.png)
![wui_formerror](https://user-images.githubusercontent.com/64965386/94757253-b352e080-0367-11eb-925d-81e8fc2052d2.png)

Also, I'm not 100% sure that what I did here is going to work, but I will test once it gets merged.  I can share how I did it with `makeStyles` if that would help with review.

2020-10-01 21:18 UTC, markrawls requested changes

2020-10-01 21:18 UTC, markrawls commented on src/input/textbox.jsx
> +
Please update `src/theme.jsx` and change the variable `redError` to this value instead of setting it inline per component.

2020-10-02 12:43 UTC, laks12metlife commented on src/input/textbox.jsx
> +
Thank you Mark!  Actually I think we might need to add `theme.palette.error.main` into `src/theme.jsx` to override the color of these 2 error messages.  I believe the color for these are determined [here for FormHelperText](https://github.com/mui-org/material-ui/blob/f013f19bc2792a25663e8a3658aed0365c0a1964/packages/material-ui/src/FormHelperText/FormHelperText.js#L20) and [here for Typography error](https://github.com/mui-org/material-ui/blob/f013f19bc2792a25663e8a3658aed0365c0a1964/packages/material-ui/src/Typography/Typography.js#L97).

2021-04-13 21:38 UTC, markrawls approved these changes

2021-04-13 21:38 UTC, merged