FRONTEND: migrate MUI v4 -> MUI v5
MetLifeLegalPlans/wui pull request #43
Opened 2021-09-22 18:38 UTC by epicoding95

This PR should contain all of the necessary code for WUI to expose MUI v5 styles/components. The only other thing needed will be the actual publishing of this package to the NPM registry.

2021-09-23 20:27 UTC, markrawls requested changes
LGTM otherwise!

2021-09-23 20:27 UTC, markrawls commented on src/theme.js
> +}
Something something "use arrow functions instead of named functions"

2021-09-24 03:36 UTC, markrawls requested changes

2021-09-24 03:36 UTC, markrawls commented on src/index.js
> +export { makeStyles, useStyles } from './theme';
I think we probably still want to export the theme object as well, right? In the current form of this PR it's inaccessible and we still need to pass it to the `ThemeProvider`.

2021-09-24 04:31 UTC, epicoding95 commented on src/index.js
> +export { makeStyles, useStyles } from './theme';
Unless i'm missing something, there is no `ThemeProvider` in wui? If we do need to access the theme, that's exactly what useStyles provides

2021-09-24 04:33 UTC, markrawls commented on src/index.js
> +export { makeStyles, useStyles } from './theme';
WUI does not expose a `ThemeProvider` but MUI does, and the app using WUI needs to put the WUI theme in there.

2021-09-24 04:39 UTC, epicoding95 commented on src/index.js
> +export { makeStyles, useStyles } from './theme';
ahh right, fixing now

2021-09-27 19:50 UTC, markrawls approved these changes
Looks good to me!

2021-09-27 19:50 UTC, merged